data:
  data_path: Week 14/hyperparameter_sweep/binary_data/hybrid/LP_with_cal_contour
  input_dir: features
  transforms: [ZScore]
  expt_ids:
    - RHT3.3.1R
    - RHT4.3.1L
    - RHT5.10.1R
    - RHT6.2.2L
    - RHT2.3.1L
    - RHT9.8.1R
    - wxf1.2.2R
    - wxf1.3.1L
    - wxf1.5.1R
    - wxf2.10.1R
    - wxf3.3.1R
    - wxf4.3.1L
    - wxf5180R
    - wxf5239R
    - wxf5272L
  seed: 43
  ignore_index: -100
  weight_classes: true
  label_names: [background, flare]
model:
  backbone: dtcn
  input_size: 18
  output_size: 2
  num_hid_units: 32
  num_layers: 3
  num_lags: 8
  seed: 43
optimizer:
  type: Adam
  lr: 0.0005
  wd: 0
  scheduler: null
training:
  device: gpu
  num_epochs: 400
  batch_size: 16
  num_workers: 4
  sequence_length: 1000
  train_probability: 0.95
  val_probability: 0.05


