data:
  data_path: c:\Columbia Capstone\Week 14\hyperparameter_sweep\binary_data\aggregate\LP_with_cal_contour
  expt_ids:
  - fighting__1.1.28R
  - fighting__1.1.28L
  - fighting__1.2.2R
  - fighting__1.2.28R
  - fighting__1.3.1R
  - fighting__1.4.1R
  - fighting__2.1.28L
  - fighting__3.1.28L
  - fighting__3.2.28L
  - hybrid__RHT3.3.1R
  - hybrid__RHT4.3.1L
  - hybrid__RHT5.10.1R
  - hybrid__RHT6.2.2L
  - hybrid__RHT2.3.1L
  - hybrid__RHT9.8.1R
  - hybrid__wxf1.2.2R
  - hybrid__wxf1.3.1L
  - hybrid__wxf1.5.1R
  - hybrid__wxf2.10.1R
  - hybrid__wxf3.3.1R
  - hybrid__wxf4.3.1L
  - hybrid__wxf5180R
  - hybrid__wxf5239R
  - hybrid__wxf5272L
  - ornamental__1.9.1R
  - ornamental__2.7.1R
  - ornamental__2.7.2R
  - ornamental__2.9.1R
  - ornamental__3.7.1R
  - ornamental__3.7.2R
  - ornamental__3.8.1R
  - ornamental__3.9.1R
  - ornamental__3.9.2R
  - ornamental__5.10.1R
  - ornamental__5.9.1R
  - ornamental__6.10.1R
  - ornamental__6.5.2R
  - ornamental__6.7.2R
  - ornamental__6.8.2R
  - ornamental__6.9.1R
  - ornamental__6.9.2R
  - wild__1.10.1R
  - wild__1.9.2R
  - wild__1381.1
  - wild__1384.2
  - wild__1434.1
  - wild__1434.2
  - wild__1436.1
  - wild__1436.2
  - wild__1437.1
  - wild__1437.2
  - wild__1438.1
  - wild__1508.1
  - wild__2.6.1R
  - wild__3.5.1R
  - fighting__1.2.2L
  - fighting__1.2.28L
  - fighting__1.3.1L
  - fighting__1.4.1L
  - fighting__2.1.28R
  - fighting__3.1.28R
  - fighting__3.2.28R
  - hybrid__RHT2.5.2R
  - hybrid__wxf1.3.2R
  - hybrid__RHT1.3.1L
  - hybrid__RHT5.2.2R
  - hybrid__wxf4.3.1R
  - ornamental__6.6.1R
  - ornamental__1.8.2L
  - ornamental__3.8.2L
  - ornamental__6.8.1R
  - ornamental__3.5.1R
  - wild__1385.1
  - wild__2.7.1R
  - wild__4.5.1R
  - wild__1381.2
  - wild__1384.1
  feature_names:
  - operculum
  - orientation
  - movement_speed
  - turning_angle
  - head_x
  - head_y
  - centroid_x
  - centroid_y
  - tail_x
  - tail_y
  - tail_angle
  - tail_dev
  - oper_angle_R
  - oper_angle_L
  - oper_dist_R
  - oper_dist_L
  - oper_angle_avg
  - oper_dist_avg
  ignore_index: -100
  input_dir: features
  label_names:
  - background
  - flare
  seed: 43
  transforms:
  - ZScore
  weight_classes: true
model:
  backbone: dtcn
  class_weights:
  - 1.0
  - 3.36975971594804
  input_size: 18
  num_hid_units: 64
  num_lags: 8
  num_layers: 3
  output_size: 2
  seed: 43
  sequence_pad: 112
optimizer:
  lr: 0.0005
  scheduler: null
  steps_per_epoch: 156
  total_steps: 62400
  type: Adam
  wd: 0
training:
  batch_size: 16
  device: gpu
  num_epochs: 400
  num_workers: 4
  sequence_length: 1000
  train_probability: 0.95
  val_probability: 0.05
version: 0.2.3
