data:
  data_path: hyperparameter_sweep/binary_data/wild/LP_with_cal_contour
  input_dir: features
  transforms: [ZScore]
  expt_ids:
    - 1.10.1R
    - 1.9.2R
    - 1381.1
    - 1384.2
    - 1434.1
    - 1434.2
    - 1436.1
    - 1436.2
    - 1437.1
    - 1437.2
    - 1438.1
    - 1508.1
    - 2.6.1R
    - 3.5.1R
  seed: 43
  ignore_index: -100
  weight_classes: true
  label_names: [background, flare]
model:
  backbone: dtcn
  input_size: 18
  output_size: 2
  num_hid_units: 64
  num_layers: 2
  num_lags: 8
  seed: 43
optimizer:
  type: Adam
  lr: 0.0001
  wd: 0
  scheduler: null
training:
  device: gpu
  num_epochs: 400
  batch_size: 16
  num_workers: 4
  sequence_length: 1000
  train_probability: 0.95
  val_probability: 0.05


